# Generated by Django 2.0.5 on 2018-07-19 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=300)),
                ('event_date', models.DateField()),
                ('pro_time_est', models.TimeField()),
                ('am_time_est', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_test_num', models.CharField(max_length=300)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobosevents.Event')),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_year', models.IntegerField(max_length=300)),
                ('bike_make', models.CharField(max_length=300)),
                ('bike_model', models.CharField(max_length=300)),
                ('bike_displacement', models.IntegerField(max_length=300)),
                ('omra_number', models.IntegerField(max_length=300)),
                ('ama_number', models.IntegerField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('address_line_two', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('zip_code', models.CharField(max_length=300)),
                ('e_c_name', models.CharField(max_length=300)),
                ('e_c_phonenumber', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSpecialTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
                ('specialtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobosevents.SpecialTest')),
            ],
        ),
        migrations.AddField(
            model_name='userevent',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobosevents.UserProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='userevent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobosevents.UserEvent'),
        ),
    ]
