# Generated by Django 2.0.5 on 2018-07-19 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('address_line_two', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('zip_code', models.CharField(max_length=300)),
                ('e_c_name', models.CharField(max_length=300)),
                ('e_c_phonenumber', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
