# Generated by Django 2.0.5 on 2018-07-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobosevents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='ama_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='bike_displacement',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='bike_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='omra_number',
            field=models.IntegerField(),
        ),
    ]
