# Generated by Django 2.0.5 on 2018-07-19 04:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lobosevents', '0002_auto_20180719_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialtest',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='specialtest',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='lobosevents.SpecialTest'),
            preserve_default=False,
        ),
    ]
