# Generated by Django 2.0.5 on 2018-07-19 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobosevents', '0003_auto_20180719_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='specialtest',
        ),
        migrations.RemoveField(
            model_name='event',
            name='userevent',
        ),
        migrations.AddField(
            model_name='specialtest',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lobosevents.Event'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lobosevents.Event'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
