# Generated by Django 2.0.5 on 2018-07-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobosevents', '0003_auto_20180719_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='am_time_est',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='pro_time_est',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
