# Generated by Django 2.0.5 on 2018-07-19 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lobosevents', '0004_auto_20180719_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='userevent',
            name='placard',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='am_time_est',
            field=models.TimeField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='pro_time_est',
            field=models.TimeField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='specialtest',
            name='special_test_num',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
