# Generated by Django 2.0.6 on 2018-07-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobosevents', '0005_auto_20180719_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='e_c_name',
            new_name='emergency_contact_contact',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='e_c_phonenumber',
            new_name='emergency_contact_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
