# Generated by Django 2.0.6 on 2018-07-19 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lobosevents', '0006_auto_20180719_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspecialtest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userspecialtest',
            name='start_time',
            field=models.TimeField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userspecialtest',
            name='stop_time',
            field=models.TimeField(blank=True, max_length=300, null=True),
        ),
    ]
