# Generated by Django 2.0.6 on 2018-07-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobosevents', '0009_auto_20180719_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birth_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
