# Generated by Django 2.0.5 on 2018-07-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=300, null=True)),
                ('model', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('starter', models.CharField(blank=True, max_length=300, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('displacement', models.IntegerField(blank=True, null=True)),
                ('seatheight', models.FloatField(blank=True, null=True)),
                ('img_src', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(blank=True, choices=[('Off-Road', 'Off-Road'), ('Motocross', 'Motocross'), ('Adventure', 'Adventure'), ('Trials', 'Trials'), ('Mini', 'Mini')], default='Off-Road', max_length=300, null=True)),
                ('engine_type', models.CharField(choices=[('Four-stroke', 'Four-stroke'), ('Two-stroke', 'Two-stroke'), ('Electric', 'Electric')], default='Four-stroke', max_length=300)),
            ],
        ),
    ]
