# Generated by Django 2.0.5 on 2018-07-04 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gomoto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikes',
            old_name='weight',
            new_name='dry_weight',
        ),
    ]
