# Generated by Django 2.0.5 on 2018-07-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomoto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='category',
            field=models.CharField(blank=True, choices=[('Off-Road', 'Off-Road'), ('Motocross', 'Motocross'), ('Adventure', 'Adventure'), ('Enduro', 'Enduro')], default='Off-Road', max_length=300, null=True),
        ),
    ]
