# Generated by Django 2.0.6 on 2018-07-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomoto', '0002_auto_20180704_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikes',
            name='horsepower',
        ),
        migrations.AddField(
            model_name='bikes',
            name='starter',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikes',
            name='wet_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='dry_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
