# Generated by Django 2.0.5 on 2018-07-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomoto', '0003_auto_20180706_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='displacement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='make',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='model',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
