# Generated by Django 2.0.5 on 2018-07-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gomoto', '0004_auto_20180708_0526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bikes',
            new_name='Bike',
        ),
    ]
