# Generated by Django 2.0.5 on 2018-07-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomoto', '0005_auto_20180708_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='img_src',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
