# Generated by Django 2.0.6 on 2018-07-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomoto', '0006_bike_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='category',
            field=models.CharField(choices=[('Off-road', 'Off-Road'), ('Motocross', 'Motocross'), ('Adventure', 'Adventure'), ('Trials', 'Trials'), ('Mini', 'Mini')], default='Off-road', max_length=300),
        ),
    ]
