# Generated by Django 2.0.6 on 2018-07-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomoto', '0007_auto_20180709_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='engine_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
