# Generated by Django 2.0.6 on 2018-07-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomoto', '0008_auto_20180709_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='engine_type',
            field=models.CharField(choices=[('Four-stroke', 'Four-stroke'), ('Two-stroke', 'Two-stroke'), ('Electric', 'Electric')], default='Four-stroke', max_length=300),
        ),
    ]
