# Generated by Django 2.0.6 on 2018-07-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomoto', '0009_auto_20180709_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='category',
            field=models.CharField(blank=True, choices=[('Off-road', 'Off-Road'), ('Motocross', 'Motocross'), ('Adventure', 'Adventure'), ('Trials', 'Trials'), ('Mini', 'Mini')], default='Off-road', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='seatheight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='starter',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
